# Generated by Django 6.0.5 on 2026-07-21 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("products", "0004_product_supplier_alter_product_category_and_more"),
        ("shops", "0003_alter_shop_options_shop_address_shop_is_active_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AIPrediction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "prediction_type",
                    models.CharField(
                        choices=[
                            ("restock", "Restock Recommendation"),
                            ("sales_forecast", "Sales Forecast"),
                            ("price_suggestion", "Price Suggestion"),
                            ("dead_stock", "Dead Stock Detection"),
                            ("demand_forecast", "Demand Forecast"),
                            ("customer_segment", "Customer Segmentation"),
                        ],
                        max_length=50,
                    ),
                ),
                ("value", models.JSONField()),
                (
                    "confidence_score",
                    models.DecimalField(decimal_places=2, default=0, max_digits=4),
                ),
                ("is_applied", models.BooleanField(default=False)),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.product",
                    ),
                ),
                (
                    "shop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_related",
                        to="shops.shop",
                    ),
                ),
            ],
            options={
                "ordering": ["-generated_at"],
            },
        ),
    ]
