# Generated by Django 6.0.5 on 2026-07-21 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shops", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="shop",
            options={"ordering": ["name"]},
        ),
        migrations.AddField(
            model_name="shop",
            name="address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="shop",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="shop",
            name="logo_url",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="shop",
            name="phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="shop",
            name="settings",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="shop",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="shop",
            name="tax_id",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="shop",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
