# Generated by Django 6.0.5 on 2026-07-21 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0003_initial"),
        ("products", "0004_product_supplier_alter_product_category_and_more"),
        ("shops", "0003_alter_shop_options_shop_address_shop_is_active_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventory",
            name="last_updated",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="inventory",
            name="reserved_quantity",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="inventorymovement",
            name="change_type",
            field=models.CharField(
                choices=[
                    ("IN", "Stock In"),
                    ("OUT", "Stock Out"),
                    ("ADJUST", "Adjustment"),
                    ("RETURN", "Return"),
                    ("TRANSFER", "Transfer"),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="inventory",
            unique_together={("shop", "product")},
        ),
    ]
