# Generated by Django 6.0.7 on 2026-07-23 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_full_name_user_phone"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="full_name",
        ),
        migrations.RemoveField(
            model_name="user",
            name="phone",
        ),
    ]
