# Generated by Django 6.0.7 on 2026-07-16 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CustomerRFM",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("recency_score", models.IntegerField()),
                ("frequency_score", models.IntegerField()),
                ("monetary_score", models.IntegerField()),
                ("rfm_score", models.IntegerField()),
                ("segment", models.CharField(max_length=100)),
                ("calculated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
