# Generated by Django 6.0.7 on 2026-07-16 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("customers", "0001_initial"),
        ("shops", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="shop",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_related",
                to="shops.shop",
            ),
        ),
    ]
