# Generated by Django 6.0.7 on 2026-07-18 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="frequency",
            field=models.PositiveIntegerField(
                default=0, help_text="Total number of orders"
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="monetary",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Total monetary value",
                max_digits=12,
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="recency_days",
            field=models.PositiveIntegerField(
                default=0, help_text="Days since last purchase"
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="rfm_score",
            field=models.PositiveSmallIntegerField(
                default=0, help_text="Combined RFM score (3-15)"
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="rfm_segment",
            field=models.CharField(
                blank=True,
                help_text="Segment name (e.g., 'Champions', 'Loyal', 'At Risk')",
                max_length=50,
                null=True,
            ),
        ),
    ]
