# Generated by Django 6.0.5 on 2026-07-20 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0003_customer_frequency_customer_monetary_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customer",
            options={},
        ),
    ]
