# Generated by Django 6.0.7 on 2026-07-23 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_initial"),
        ("shops", "0003_alter_shop_options_shop_address_shop_is_active_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="shop",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_related",
                to="shops.shop",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="shop",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_related",
                to="shops.shop",
            ),
        ),
    ]
