# Generated by Django 6.0.5 on 2026-07-26 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_product_supplier_alter_product_category_and_more"),
        ("shops", "0003_alter_shop_options_shop_address_shop_is_active_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="category",
            unique_together={("shop", "name")},
        ),
    ]
