# Generated by Django 6.0.7 on 2026-08-11 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_alter_category_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="category",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.RemoveField(
            model_name="category",
            name="shop",
        ),
    ]
