# Generated by Django 6.0.7 on 2026-08-21 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "products",
            "0006_alter_category_unique_together_alter_category_name_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="brand",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.RemoveField(
            model_name="product",
            name="barcode",
        ),
        migrations.DeleteModel(
            name="Brand",
        ),
    ]
