# Generated by Django 6.0.7 on 2026-09-20 06:32

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


def convert_prices_to_percentages(apps, schema_editor):
    """Convert existing absolute discount_price values into equivalent
    discount_percentage values so no configured discount is lost."""
    Product = apps.get_model("products", "Product")
    for product in Product.objects.exclude(discount_price__isnull=True):
        if product.sale_price and product.sale_price > 0 and product.discount_price < product.sale_price:
            product.discount_percentage = (
                (product.sale_price - product.discount_price) / product.sale_price * Decimal("100")
            )
            product.save(update_fields=["discount_percentage"])


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0007_alter_product_brand_remove_product_barcode_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="discount_percentage",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Discount as a percentage of the sale price (0-100).",
                max_digits=5,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0")),
                    django.core.validators.MaxValueValidator(Decimal("100")),
                ],
            ),
        ),
        migrations.RunPython(convert_prices_to_percentages, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="product",
            name="discount_price",
        ),
    ]
